# Spec Kit Configuration for Ascended Social
project:
  name: "ascended-social"
  description: "Mystical social media platform for spiritual engagement"
  version: "1.0.0"
  
ai_assistant: "replit-agent"  # Using Replit Agent instead of Claude/Copilot
agents:
  primary: "replit-agent"
  fallback: ["claude", "copilot"]

directories:
  specs: ".specify/specs"
  plans: ".specify/plans" 
  tasks: ".specify/tasks"
  implementations: "."

templates:
  spec: ".specify/templates/spec.md"
  plan: ".specify/templates/plan.md"
  task: ".specify/templates/task.md"

workflow:
  phases:
    - "specify"
    - "plan"
    - "tasks"
    - "implement"
  
  checkpoints:
    - "spec_review"
    - "plan_approval"
    - "task_breakdown"
    - "implementation_complete"